---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'alesandapres'
#Minify Requirements
Minify_Requirements_Backend:
  rewrite_uris: 'true'
Director:
  environment_type: 'live'